/**
 * @file Explicit, deployment-level runtime mode (issue #245). Generated by
 * scripts/package-artifact.py (issue #247) — not personal or secret, safe
 * to publish. One of "owner", "local", "viewer"; see README.md.
 */

window.OSKARS_RUNTIME_MODE = "local";
