/**
 * @file Explicit deployment mode and account policy (issues #245/#332).
 * Generated by scripts/package-artifact.py — not personal or secret, safe
 * to publish. See README.md.
 */

window.OSKARS_RUNTIME_MODE = "local";
window.OSKARS_ACCESS_POLICY = "account";
