/**
 * @file Explicit deployment mode (issue #245).
 * Generated by scripts/package-artifact.py — not personal or secret, safe
 * to publish. See README.md.
 */

window.OSKARS_RUNTIME_MODE = "local";
